#!/bin/sh

# Usage: mill import <name> "<url>"
# Summary: Import a document and convert to Markdown.
# Help: Fetches HTML from the given URL from the net 
# and converts it to Markdown with 'pandoc'.
#
#   mill import Pandoc "http://johnmacfarlane.net/pandoc/README.html"
#

set -e

. $_MILL_ROOT/share/mill/global.functions
source $_MILL_ROOT/share/mill/local.config


# # VARS

DOCNAME="$1"
URL="$2"

TMP_DOC="."$DOCNAME".tmp.html"


# # FUNCTIONS

function fetch_from_url()
{
    echo "    [#] Fetching \"$URL\""
    curl \
	-o "$TMP_DOC" \
	"$URL" |while read REPLY; do echo "    [#] $REPLY"; done \
    && echo "    [!] SUCCESS"
    # TODO: how to get remote filename (-O/-J) from curl so we know which file was fetched?
}

function import_from_file()
{
    echo "    [#] Converting \"$DOCNAME\""
    ~/.cabal/bin/pandoc \
	-i "$URL" \
	-o "$TMP_DOC" \
	|while read REPLY; do echo "    [#] $REPLY"; done \
    && echo "    [!] SUCCESS"
}


# # MAIN

echo "[>] Importing \"$DOCNAME\""

fetch_from_url
import_from_HTML

echo "[<] Imported \"$DOCNAME\""

# Try to open the imported document.
mill shim open ""$DOCNAME".markdown"