#!/bin/sh

# MILL NEW #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Usage: mill new <NAME> [stationery]
# Summary: Make a blank paper from the stationery.
# Help: Create a new folder with the name you choose
# and some content to get you started.
# Optionally choose a stationery (default is Paper).
#
# Stationaries:
# * Simple
# * Paper
# * Thesis (not implemented)

set -e

. $_MILL_ROOT/share/mill/global.functions
source $_MILL_ROOT/share/mill/local.config

# # VARS

NAME="$1"
STATIONERY="$2"

# If no stationery was supplied
if [[ "$STATIONERY" = "" ]]; then
    # The default type of stationery is "Paper"
    STATIONERY="Paper"
fi


# # FUNCTIONS

function create_project()
{
    mkdir "$NAME"
    cd "$NAME"
}

function get_stationery_from_git()
{
    TMPDIR="$(mktemp -d /tmp/papermill-new.XXXXXX)" \
    && git clone -q --depth=1 "$STATIONERY_REPO" "$TMPDIR" \
    && cp -R ""$TMPDIR"/"$STATIONERY"/" . \
    && mv "Document.markdown" "$NAME.markdown"
}

function setup_config()
{
    case $STATIONERY in
        Simple )
            local file=".papermill"
        ;;
        Paper|Thesis )
            local folder=".papermill"
            local file=""$folder"/papermill.config"
            mkdir -p "$folder"
        ;;
    esac
    
    # Try to create or update the project config file.
    touch "$file"
    
    # Test if it this failed, bail out if it did.
    if [[ $? != 0 ]]; then
        echo "Could not create \"$file\""
        return 1
    fi
    
    # Now let's fill up this config -- we'll start with a heading and the date.
    echo "# PAPERMILL PROJECT CONFIGURATION" >> $file
    echo "# " >> $file
    echo "# -- started on $(date) -- " >> $file
    
    # Lastly, we copy the user config from the line 13 and below to complete the project config.
    tail -n +13 $_MILL_ROOT/share/mill/user.config >> $file
}

function start_new_git_repo()
{
    git init -q \
    && git add --all \
    && git commit -m "Starting $NAME" |while read REPLY; do echo "    [-] $REPLY"; done \
    && echo "    [#] SUCCESS!" \
    && echo "[!] If you don't want git, just delete the .git folder."
}

# # MAIN

# Do all the needed functions in single steps,
# only continue if the last step did not fail.

# for STEP in \
#     create_project \
#     get_stationery_from_git \
#     setup_config \
#     start_new_git_repo
# do
#     echo "$STEP"
# done

echo "[>] Creating new "$STATIONERY" in /"$NAME""
create_project
if [[ $? != 0 ]]; then
    echo "    [X] FAIL!"
    exit 1
fi

echo "    [#] Getting and unwrapping the stationery."
get_stationery_from_git
if [[ $? != 0 ]]; then
    echo "    [X] FAIL!"
    exit 1
fi

echo "    [#] Setting up project config."
setup_config
if [[ $? != 0 ]]; then
    echo "    [X] FAIL!"
    exit 1
fi

echo "    [#] Initializing version control."
start_new_git_repo
if [[ $? != 0 ]]; then
    echo "    [X] FAIL!"
    exit 1
fi


# Since all is well, we try to open the new project folder (in the background).
mill shim open "." &
# and the same with the new Markdown file.
mill shim open "$NAME.markdown" &

echo "[<] Finished creating new $STATIONERY in /$NAME"

exit 0