#!/bin/sh

# Usage: mill update
# Summary: Update mill cli tool from git.
# Help: Selfupdate which pulls from the repo on github.
#

set -e

. $_MILL_ROOT/share/mill/global.functions
source $_MILL_ROOT/share/mill/local.config

# # MAIN

echo "Updating mill in "$_MILL_ROOT" ..."
cd $_MILL_ROOT
git pull -q origin master \
&& echo "SUCCESS" \
|| echo "FAIL"