#!/usr/bin/env sh
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# MILL UPDATE #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Usage: mill update
# Summary: Update mill cli tool from git.
# Help: Selfupdate which pulls from the repo on github.
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

set -e
echo "Updating mill in "$_MILL_ROOT" ..."
cd $_MILL_ROOT
git pull -q origin master \
&& echo "SUCCESS" \
|| echo "FAIL"