#!/bin/sh

# MILL WEB  #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Usage: mill web
# Summary: Output to HTML
# Help: Use this to output the document to a format suitable for
# the web (HTML).
#

set -e

. $_MILL_ROOT/share/mill/global.functions
source $_MILL_ROOT/share/mill/local.config


# Find every markdown file and start a loop for it
echo "[>] Output to WEB ..."

prepare_output_folder

for INPUTFILE in $(find *.markdown -maxdepth 0 -type f -not \( -name "images" \))
do

    # Process MARKDOWN Files
    echo "   [#] Generating HTML: $INPUTFILE ..."
    OUTPUTFILE=""$OUTPUT_DIR"/"$INPUTFILE".generated.html"
    {
    	$(mill shim pandoc) "$INPUTFILE" \
    	--write=html5 --standalone --smart --toc --section-divs --normalize --number-sections \
    	--bibliography="./bibliography.bib" \
    	--csl=".papermill/din-1505-2.csl" \
    	--output="$OUTPUTFILE"
    } && {
        # If the last operation was successfull, tell it to the user and set the exit status to '0'.
	    echo "   [!] SUCCESS"
        EXIT_STATUS=0
        # We also try to open the output file
		mill shim open "$OUTPUTFILE"
    }
done
# END Process MARKDOWN Files

echo "[<] Finished output to WEB ..."

# EXIT with status
if [[ "$EXIT_STATUS" = "" ]]; then
    # If no status was set, something is wrong, so we set 1.
    EXIT_STATUS=1
fi
exit $EXIT_STATUS