#!/bin/sh

# MILL NEW #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Usage: mill new <NAME> [stationery]
# Summary: Make a blank paper from the stationery.
# Help: Create a new folder with the name you choose
# and some content to get you started.
# Optionally choose a stationery (default is Paper).
#
# Stationaries:
# * Simple
# * Paper
# * Thesis

set -e

. $_MILL_ROOT/share/mill/global.functions
source $_MILL_ROOT/share/mill/local.config

# # VARS

NAME="$1"

# The default type of stationery is "Paper"
STATIONERY="Paper"

# # FUNCTIONS
function get_stationery_from_git()
{
    TMPDIR="$(mktemp -d /tmp/papermill-new.XXXXXX)" \
    && git clone -q --depth=1 "$STATIONERY_REPO" "$TMPDIR" \
    && cp -R "$TMPDIR"/"$STATIONERY"/ . \
    && mv "Document.markdown" ""$NAME".markdown"
}

function start_new_git_repo()
{
    git init -q \
    && git add --all \
    && git commit -m "Starting $NAME" |while read REPLY; do echo "    [#] $REPLY"; done \
    && echo "    [#] SUCCESS!"
}

# # MAIN

echo "[>] Creating new "$STATIONERY" in /"$NAME""
mkdir "$NAME" && cd "$NAME" \
&& get_stationery_from_git \
&& start_new_git_repo \
&& echo "[<] Started new "$STATIONERY" in /"$NAME"" \
&& echo "[!] If you don't want git, just delete the .git folder." \
&& mill shim open "." \
mill shim open ""$NAME".markdown"
