#!/bin/sh

# MILL NEW #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Usage: mill new <NAME>
# Summary: Make a blank paper from the stationery.
# Help: Create a new folder with the name you choose
# and some content to get you started.
#

set -e
source $_MILL_ROOT/share/mill/local.config

NAME="$1"

echo "[>] Creating new Paper in /"$NAME""

git clone -q "$STATIONERY_REPO" "$NAME" \
&& cd "$NAME" \
&& rm -rf .git \
&& git init -q \
&& git add --all \
&& git commit -m "Starting $NAME" |while read REPLY; do echo "    [#] $REPLY"; done \
&& echo "    [#] SUCCESS!" \
&& echo "[<] Started new Paper in /"$NAME"" \
&& echo "[!] If you don't want git, just delete the .git folder."
